[package]
name = "far"
version = "0.1.0"
authors = ["wiryls"]
edition = "2018"

[[bin]]
name = "far"
path = "src/main.rs"

[lib]
name = "far"
path = "src/lib.rs"

[dependencies]
regex = "1"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4"
